projects:
  app:
    schemaPath: "src/schema/index.graphql"
    extensions:
      endpoints:
        default: "http://localhost:${env:PORT}"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
